### PR TITLE
Fixing clean architecture

### LINKED ISSUE #64: Fixing Clean Architecture Violations
While making our class UML diagram and package diagram, many undesirable dependencies became apparent that either strongly violated the clean architecture (going from inner layer to outer layer) or were just not ideal (skipping from outer layer to multiple layers down). We should remove these dependencies through the creation of new intermediate use case classes as well as dependency injection/inversion.
Each box should be checked when the given dependency is removed/inverted/injected

- [x] package fetchers -> package server
    - [x] LoanDataFetcher -> Env
    - [x] DataBaseFetcher -> Env
- [x] package server -> package fetchers
    - [x] Server -> DataBaseFetcher
- [x] package routes -> package entities
    - [x] Search -> Car (maybe)
- [x] package fetchers -> package entities
    - [x] LoanDataFetcher -> CarBuyer (see note)
    - [x] LoanDataFetcher -> Car (see note)
- [x] package fetchers -> package entityparsers
    - [x] LoanDataFetcher -> JsonParser
- [x] package fetchers -> outside libraries
    - [x] LoanDataFetcher -> JsonObject
    - [x] LoanDataFetcher -> JsonArray
    - [x] LoanDataFetcher -> HTTPURLConnection (see second note)
    - [x] DataBaseFetcher -> SQL stuff (see second note)
- [x] packages routes, fetchers -> package logging (maybe)
    - [x] If we want, we could have a single Logger constructed in Server that gets passed as a parameter to everything else. This would get rid of the harder dependencies currently seen, and I kind of like the consistency of only having one Logger for the entire program. But this isn't essential - I don't necessarily think Logger is really part of our clean architecture.

With LoanDataFetcher and DataBaseFetcher, we really just need to extract out a few lower-layer classes; the highest level fetcher class shouldn't depend on the Entities, but the lower level ones probably will need to. 
Also, LoanDataFetcher and DataBaseFetcher shouldn't directly be handling HTTP/SQL stuff - there should be an interface between them, where HTTP and SQL are just implementations of that interface

There might be some bad dependencies I missed here, so we should try to add them to this list as we discover them, then check them off once they're resolved.

### PR DESCRIPTION
**Pull request by gnguralnick**
This PR resolves the clean architecture violations we found while making our class and package diagrams for phase 1.
It's main effect is to split each of LoanDataFetcher and DataBaseFetcher into multiple different classes; rather than handling HTTP and database connections, fetching, and entity instantiation all in one class (violating single responsibility and introducing many dependencies), we now have separate classes for each of these functions.
First, I extracted PostgresDataBase from DataBaseFetcher, which contains the connectAndMigrate and insertPlaceHolderData to handle the database connection and instantiation. It also has an executeQuery method which handles actually sending a request to the database. This class extends the abstract DataBase class, so that if we want to change our database implementation in the future we can.
I also made a Fetcher interface, with implementers HTTPFetcher and DataBaseFetcher, to standardize the process of making fetch requests and allow for dependency injection of Fetcher stuff into the FetchUseCases (so that these use cases no longer have dependencies on HTTP and SQL libraries).
For the Loan route, we now have:
 - HTTPFetcher, which handles making a connection over HTTP and processing requests to and from the connection
 - FetchLoanDataUseCase, which accepts Fetchers for rate and score requests as instance attributes and uses them to make requests for LoanData information given a Car and CarBuyer
For the Search and AddOns routes, we now have:
 - DataBaseFetcher, which accepts a DataBase as an instance variable and handles making queries to the database
 - FetchCarDataUseCase, which accepts a Fetcher and makes requests for Cars given either a car ID or a search string
 - FetchAddOnDataUseCase, which accepts a Fetcher and makes requests for a List of AddOns given a car ID
I also removed dependencies on Env by making those dependencies into instance attributes and injecting them into the constructors - because of this, I needed to move Routes into the server package so that it could access Env and pass the values into the Route constructors.
Similarly, I altered our logger process so that only a single Logger instance is constructed Server.java, which is then passed into each of the routes as an instance attribute.
I also made exception messages more descriptive and better formatted and ensured they all get logged in the console when caught.

There might be a few other changes I missed here (oops).

With regards to testing, there aren't currently any unit tests for the Routes, Database, or HTTP stuff, as I wasn't sure how unit testing of those things would work. That being said, everything Works on My Machine (TM).

Closes #64

### CODE REVIEW

File: src/main/java/server/Routes.java [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+
+/** A class wrapping all the routes of the program. */
+public class Routes {
+    /** The routes of the program. */
+    public static final Route[] routes = {
+        new Loan(Env.SENSO_RATE_URL, Env.SENSO_SCORE_URL, Server.logger),
+        new Search(Server.dataBase, Server.logger),
+        new Addons(Server.dataBase, Server.logger),
+    };
+}
```
Comment (Mogtaba-Alim) [inline src/main/java/server/Routes.java:16]: Why was the Routes file moved from the routes folder to the server folder?

Comment (gnguralnick) [reply src/main/java/server/Routes.java:16]: This was so that it could access the URLs in Env without creating a dependency between the routes package and the server package. Also, nothing in the routes package accesses Routes, but the stuff in the server package does, so we may as well have it there.

File: src/main/java/routes/Loan.java [hunk 2]
```diff
@@ -12,50 +14,76 @@
...
     public String getContext() {
         return "/loan";
     }
 
+    public Loan(URL SENSO_RATE_URL, URL SENSO_SCORE_URL, Logger logger) {
+        super(logger);
+        this.SENSO_RATE_URL = SENSO_RATE_URL;
+        this.SENSO_SCORE_URL = SENSO_SCORE_URL;
+    }
+
```
Comment (Mogtaba-Alim) [inline src/main/java/routes/Loan.java:45]: Whats the function of logger being in the constructor of the routes?

**Review by Mogtaba-Alim — APPROVED** [review]
Seems fine. All tests pass. All functionality works when program is running.

File: src/main/java/routes/Loan.java (hunk 2 above)
Comment (gnguralnick) [reply src/main/java/routes/Loan.java:45]: this is instead of having the routes call LoggerFactory.getLogger, removing the dependency on the logging package
we can use it as an example of dependency injection
