### PR TITLE
Intellij warning fixes

### LINKED ISSUE #56: Fix Intellij warnings before phase 1 submission

### PR DESCRIPTION
**Pull request by Mogtaba-Alim**
Fixed some declaration redundancies, code maturity and error handling issues, as well as minor errors and typos to remove intelijjs warnings

Closes #56.

### CODE REVIEW

File: src/main/java/entities/Car.java [hunk 1]
```diff
@@ -105,7 +105,7 @@ public double getPrice() {
     /**
      * Updates this Car's price to the specified value.
      *
-     * @param price
+     * @param price The cars price
```
Comment (mtoohey31) [inline src/main/java/entities/Car.java:108]: Could be `The car's price`

File: src/main/java/entities/Car.java [hunk 2]
```diff
@@ -132,7 +132,7 @@ public String getModel() {
     /**
      * Returns this Car's model year
      *
-     * @return
+     * @return The cars model year
```
Comment (mtoohey31) [inline src/main/java/entities/Car.java:135]: Could be `The car's model year`

File: src/main/java/entities/CarBuyer.java [hunk 3]
```diff
@@ -14,8 +14,8 @@
     /**
      * Constructs a new CarBuyer with the specified budget and credit score.
      *
-     * @param budget
-     * @param creditScore
+     * @param budget The car buyers budget for the car with addons
+     * @param creditScore The car buyers credit score
```
Comment (mtoohey31) [inline src/main/java/entities/CarBuyer.java:18]: `buyers` could be `buyer's`

File: src/main/java/entities/CarBuyer.java [hunk 4]
```diff
@@ -25,7 +25,7 @@ public CarBuyer(double budget, int creditScore) {
     /**
      * Returns this CarBuyer's budget.
      *
-     * @return
+     * @return the car buyers budget
```
Comment (mtoohey31) [inline src/main/java/entities/CarBuyer.java:28]: Same here with `buyer's`

File: src/main/java/entities/CarBuyer.java [hunk 5]
```diff
@@ -34,7 +34,7 @@ public double getBudget() {
     /**
      * Returns this CarBuyer's credit score.
      *
-     * @return
+     * @return the car buyers credit score
```
Comment (mtoohey31) [inline src/main/java/entities/CarBuyer.java:37]: And same here

File: src/main/java/entities/LoanData.java [hunk 6]
```diff
@@ -85,7 +85,7 @@ public void setInstallment(double installment) {
     /**
      * Returns this loan's amortization table
      *
-     * @return
+     * @return The loans' amortization table
```
Comment (mtoohey31) [inline src/main/java/entities/LoanData.java:88]: Should be `loan's` instead of `loans'`.

File: src/main/java/entityparsers/JsonParser.java [hunk 7]
```diff
@@ -34,10 +34,10 @@ public AttributeMap parse() throws Exceptions.ParseException {
      * The recursive helper method for parse(). This method is recursive since JsonObjects can
      * contain other JsonObjects.
      *
-     * @param object the given JsonObject used to create the AttributeMap
-     * @return AttributeMap
+     * @param object The JsonObject to be converted to be parsed
+     * @return an attribute map representing the JsonObject
      * @throws constants.Exceptions.ParseException if the JsonObject is not a String, Number, or
-     *     Object
+     *     Objec
```
Comment (mtoohey31) [inline src/main/java/entityparsers/JsonParser.java:40]: This should probably be left as `Object` right?

File: src/main/java/server/main.java [hunk 8]
```diff
@@ -27,6 +27,7 @@ public static void main(String[] args) {
                 try {
                     Thread.sleep(1000);
                 } catch (InterruptedException te) {
+                    // Catch block is currently empty
```
Comment (mtoohey31) [inline src/main/java/server/main.java:30]: We should probably explain why this doesn't need to be handled, basically from what I understand it'll only be interrupted if the program is stopped while it's sleeping, in which case the program is already exiting and we don't need to report any errors.

**Review by mtoohey31 — CHANGES_REQUESTED** [review]
Overall very awesome, IntelliJ seems much less angry now, just a few small things. Also, I'm not sure what the spec says, but are we supposed to capitalize the text following parameters, exceptions, and returns in Javadocs, or is the phrase supposed to begin with lowercase? I just noticed while scrolling through all the changes that we aren't consistent with one or the other, it's not really that important though if we don't want to worry about it.

File: src/main/java/entities/CarBuyer.java (hunk 4 above)
Comment (mtoohey31) [reply src/main/java/entities/CarBuyer.java]: Nvm, apparently IntelliJ doesn't like apostrophes here.

**Comment by mtoohey31** [comment]
This closes #56.

**Review by mtoohey31 — APPROVED** [review]
